domain_path: A:\ECE544_GitHub\ece544w25_proj1_release_1_0\vitis\platform\export\platform\sw\standalone_microblaze_0
app_src_dir: A:\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
