# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/embsys_microblaze_mcs_0_0.xci
# IP: The module: 'embsys_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/bd_0ac7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7 || ORIG_REF_NAME==bd_0ac7} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0ac7_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_microblaze_I_0 || ORIG_REF_NAME==bd_0ac7_microblaze_I_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0ac7_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_rst_0_0 || ORIG_REF_NAME==bd_0ac7_rst_0_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_0ac7_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_ilmb_0 || ORIG_REF_NAME==bd_0ac7_ilmb_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0ac7_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_dlmb_0 || ORIG_REF_NAME==bd_0ac7_dlmb_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_0ac7_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_dlmb_cntlr_0 || ORIG_REF_NAME==bd_0ac7_dlmb_cntlr_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_0ac7_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_ilmb_cntlr_0 || ORIG_REF_NAME==bd_0ac7_ilmb_cntlr_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0ac7_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_lmb_bram_I_0 || ORIG_REF_NAME==bd_0ac7_lmb_bram_I_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0ac7_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_mdm_0_0 || ORIG_REF_NAME==bd_0ac7_mdm_0_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_8/bd_0ac7_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_xlconcat_0_0 || ORIG_REF_NAME==bd_0ac7_xlconcat_0_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_0ac7_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_iomodule_0_0 || ORIG_REF_NAME==bd_0ac7_iomodule_0_0} -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0ac7_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_microblaze_I_0 || ORIG_REF_NAME==bd_0ac7_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0ac7_microblaze_I_0_ooc_debug.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0ac7_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_rst_0_0 || ORIG_REF_NAME==bd_0ac7_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0ac7_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_rst_0_0 || ORIG_REF_NAME==bd_0ac7_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0ac7_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_dlmb_0 || ORIG_REF_NAME==bd_0ac7_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0ac7_lmb_bram_I_0_ooc.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0ac7_mdm_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_mdm_0_0 || ORIG_REF_NAME==bd_0ac7_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0ac7_mdm_0_0_ooc_trace.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_0ac7_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_iomodule_0_0 || ORIG_REF_NAME==bd_0ac7_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/bd_0ac7_ooc.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/embsys_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/embsys_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/embsys_microblaze_mcs_0_0.xci
# IP: The module: 'embsys_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/bd_0ac7.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7 || ORIG_REF_NAME==bd_0ac7} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0ac7_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_microblaze_I_0 || ORIG_REF_NAME==bd_0ac7_microblaze_I_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0ac7_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_rst_0_0 || ORIG_REF_NAME==bd_0ac7_rst_0_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_0ac7_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_ilmb_0 || ORIG_REF_NAME==bd_0ac7_ilmb_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0ac7_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_dlmb_0 || ORIG_REF_NAME==bd_0ac7_dlmb_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_0ac7_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_dlmb_cntlr_0 || ORIG_REF_NAME==bd_0ac7_dlmb_cntlr_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_0ac7_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_ilmb_cntlr_0 || ORIG_REF_NAME==bd_0ac7_ilmb_cntlr_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0ac7_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_lmb_bram_I_0 || ORIG_REF_NAME==bd_0ac7_lmb_bram_I_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0ac7_mdm_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_mdm_0_0 || ORIG_REF_NAME==bd_0ac7_mdm_0_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_8/bd_0ac7_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_xlconcat_0_0 || ORIG_REF_NAME==bd_0ac7_xlconcat_0_0} -quiet] -quiet

# IP: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_0ac7_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0ac7_iomodule_0_0 || ORIG_REF_NAME==bd_0ac7_iomodule_0_0} -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0ac7_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_microblaze_I_0 || ORIG_REF_NAME==bd_0ac7_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_0ac7_microblaze_I_0_ooc_debug.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0ac7_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_rst_0_0 || ORIG_REF_NAME==bd_0ac7_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_0ac7_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_rst_0_0 || ORIG_REF_NAME==bd_0ac7_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_0ac7_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_dlmb_0 || ORIG_REF_NAME==bd_0ac7_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_0ac7_lmb_bram_I_0_ooc.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0ac7_mdm_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_mdm_0_0 || ORIG_REF_NAME==bd_0ac7_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_0ac7_mdm_0_0_ooc_trace.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_0ac7_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ac7_iomodule_0_0 || ORIG_REF_NAME==bd_0ac7_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/bd_0/bd_0ac7_ooc.xdc

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/embsys_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_microblaze_mcs_0_0/embsys_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
