# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: A:/ECE544_GitHub/ece544_Proj1/constraints/nexysA7fpga.xdc

# Block Designs: bd/embsys/embsys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_mcs_0_0/embsys_microblaze_mcs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_mcs_0_0 || ORIG_REF_NAME==embsys_microblaze_mcs_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rgbPWM_0_0/embsys_rgbPWM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_rgbPWM_0_0 || ORIG_REF_NAME==embsys_rgbPWM_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_proc_sys_reset_0_0/embsys_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_proc_sys_reset_0_0 || ORIG_REF_NAME==embsys_proc_sys_reset_0_0} -quiet] -quiet

# XDC: a:/ECE544_GitHub/ece544_Proj1/project_1/project_1.gen/sources_1/bd/embsys/embsys_ooc.xdc
