#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_0_IS_DUAL 0x0
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x20

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x20
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x0
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x1
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x5f5e100

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x5f5e100

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral MDM_1 */
#define XPAR_MDM_1_COMPATIBLE "xlnx,mdm-3.2"
#define XPAR_MDM_1_BASEADDR 0x41400000
#define XPAR_MDM_1_HIGHADDR 0x41400fff
#define XPAR_MDM_1_BAUDRATE 0x0
#define XPAR_MDM_1_USE_PARITY 0x0
#define XPAR_MDM_1_ODD_PARITY 0x0
#define XPAR_MDM_1_DATA_BITS 0x0

/* Canonical definitions for peripheral MDM_1 */
#define XPAR_XUARTLITE_0_BASEADDR 0x41400000
#define XPAR_XUARTLITE_0_HIGHADDR 0x41400fff
#define XPAR_XUARTLITE_0_BAUDRATE 0x0
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,mdm-3.2"
#define XPAR_XUARTLITE_0_DATA_BITS 0x0
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral PWM_ANALYZER_0 */
#define XPAR_PWM_ANALYZER_0_BASEADDR 0x44a10000
#define XPAR_PWM_ANALYZER_0_HIGHADDR 0x44a1ffff

/* Canonical definitions for peripheral PWM_ANALYZER_0 */
#define XPAR_PWM_ANALYZER_0_BASEADDR 0x44a10000
#define XPAR_PWM_ANALYZER_0_HIGHADDR 0x44a1ffff

/* Definitions for peripheral PWM_ANALYZER_1 */
#define XPAR_PWM_ANALYZER_1_BASEADDR 0x44a20000
#define XPAR_PWM_ANALYZER_1_HIGHADDR 0x44a2ffff

/* Canonical definitions for peripheral PWM_ANALYZER_1 */
#define XPAR_PWM_ANALYZER_1_BASEADDR 0x44a20000
#define XPAR_PWM_ANALYZER_1_HIGHADDR 0x44a2ffff

/* Definitions for peripheral PWM_ANALYZER_2 */
#define XPAR_PWM_ANALYZER_2_BASEADDR 0x44a30000
#define XPAR_PWM_ANALYZER_2_HIGHADDR 0x44a3ffff

/* Canonical definitions for peripheral PWM_ANALYZER_2 */
#define XPAR_PWM_ANALYZER_2_BASEADDR 0x44a30000
#define XPAR_PWM_ANALYZER_2_HIGHADDR 0x44a3ffff

/* Definitions for peripheral NEXYS4IO_0 */
#define XPAR_NEXYS4IO_0_BASEADDR 0x44a00000
#define XPAR_NEXYS4IO_0_HIGHADDR 0x44a0ffff

/* Canonical definitions for peripheral NEXYS4IO_0 */
#define XPAR_NEXYS4IO_0_BASEADDR 0x44a00000
#define XPAR_NEXYS4IO_0_HIGHADDR 0x44a0ffff

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0xffff
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define STDOUT_BASEADDRESS 0x41400000
#define STDIN_BASEADDRESS 0x41400000

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */